### PR TITLE
Editbox, Spellbook, Kill.lua

### PR DESCRIPTION
**Pull request by Kkthnx**

### CODE REVIEW

**Comment by Grimsbain** [comment]
Not sure if hiding the chat input is really needed. As soon as you use it the bar is visible for the rest of the session and it may confuse some people that you cant use the mouse to make it show up.

**Comment by Kkthnx** [comment]
When the player enters the world the Editbox is shown but faded. Once you use it, it fixes itself. This doesn't hide it. It only hides it to ensure it not shown when player logins. It works like normal.

**Comment by Grimsbain** [comment]
It may just confuse people that they can't click on it when they first login.

https://youtu.be/19_UGOeKD1o

**Comment by Kkthnx** [comment]
Why does your editbox remain visible after being unfocused?

**Comment by Grimsbain** [comment]
I copied in the exact code from your pull request and mine doesn't do that. I'm on the beta and it looks like you are on the ptr but I don't see why that would matter to this issue. But I do know how to make the input box do this if this is something we would want to do.

**Comment by Kkthnx** [comment]
There is no need for all the extra code. Clean install the UI and only use NeavUI addons. Im on the beta as well. There is no code in NeavUI that supports the Editbox being faded like so in your video so. Clean instal and let me know.

**Comment by Kkthnx** [comment]
I'll let you handle this. I'll just let @renstrom pull anything from my repo if he wants it.

https://github.com/Kkthnx/NeavUI

**Pull request closed without merging**
