### PR TITLE
basic hp percentage text in nPower

### PR DESCRIPTION
**Pull request by srliao**
this commit relates to #230 

added very basic hp percentage text above nPower mana/power bar. can be turned on/off in configs. default option is off

### CODE REVIEW

**Comment by srliao** [comment]
image

Currently looks like this on default settings. Need to maybe add some code to shift it up automatically if extraPoints are enabled. But need to detect based on stance etc... since otherwise druid will automatically have it pushed up even if not in cat form

**Comment by srliao** [comment]
Got rid of HP position option. Instead made the HP display move based on if f.extraPoint exists or not.

Added extra check for druid where HP is only shifted up in cat form OR has combo points. Looks like following right now:

image

image

image

**Comment by renstrom** [comment]
Sorry for being so slow on the feedback. I actually did something similar a long time ago, but instead of just numbers I used a status bar. It looked almost identical to the power bar, just in different colours.

**Comment by renstrom** [comment]
I'm gonna merge this, but I might have another go at making a health bar again (as a separate addon kind of like nPower, it's called "power" after all). If only to have the same features as the stock UI with the new resource bar thingie.... Hmm, I might even rename it nResources 🤔

**Comment by renstrom** [comment]
Seems like there was a also a minor bug when the hp text was turned off. I just pushed a fix (https://github.com/renstrom/NeavUI/commit/e55b65ae763b47830d08bdcc3ac9f67c6efe9c82).

**Comment by srliao** [comment]
Thanks! I had fixed that bug locally but forgot to push the changes :sweat_smile: :sweat_smile:

**Pull request merged**
